CREATE TABLE T_USERS(
	ID NUMBER(6) PRIMARY KEY,
	USERNAME VARCHAR2(20) NOT NULL UNIQUE,
	USERPWD VARCHAR2(20) NOT NULL 
);

CREATE SEQUENCE T_USERS_ID_SEQ
			START WITH 1
 			INCREMENT BY 1
 			NOCACHE;